modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/McMelonTV/InventoryOverhaul/issues"
license = "MIT"

[[mods]]
modId = "inventoryoverhaul"
version = "${version}"
displayName = "InventoryOverhaul"
authors = "mel (https://github.com/McMelonTV)"
description = '''
A mod that aims to improve inventory management by changing the core aspects of the player's inventory and hotbar.
'''
logoFile = "assets/inventoryoverhaul/icon.png"

[[dependencies.inventoryoverhaul]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.inventoryoverhaul]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.inventoryoverhaul]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "inventoryoverhaul.mixins.json"
